package org.alex_melan.spacereloaded.registry;

import net.minecraft.world.level.material.MapColor;

import java.util.Map;

/**
 * Цвет блоков мода на картах и орбитальных снимках — «вид сверху»: ближайший цвет палитры к среднему
 * цвету верхних граней модели. Сгенерировано tools/gen_map_colors.py, руками не править.
 */
public final class ModMapColors {

    private static final Map<String, MapColor> COLORS = Map.ofEntries(
        Map.entry("air_separator", MapColor.WOOL),
        Map.entry("airlock_pump", MapColor.DEEPSLATE),
        Map.entry("al_li_fuel_tank", MapColor.GLOW_LICHEN),
        Map.entry("aluminium_fuel_tank", MapColor.COLOR_LIGHT_GRAY),
        Map.entry("anorthosite", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("assembly_pylon", MapColor.COLOR_GRAY),
        Map.entry("assembly_table", MapColor.COLOR_GRAY),
        Map.entry("asteroid_stone", MapColor.COLOR_GRAY),
        Map.entry("asu_compressor", MapColor.TERRACOTTA_CYAN),
        Map.entry("asu_heat_exchanger", MapColor.WOOL),
        Map.entry("asu_sump", MapColor.COLOR_BLUE),
        Map.entry("asu_tray", MapColor.CLAY),
        Map.entry("atmosphere_controller", MapColor.COLOR_LIGHT_GRAY),
        Map.entry("atmospheric_collector", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("battery", MapColor.STONE),
        Map.entry("beo_reflector", MapColor.WOOL),
        Map.entry("beryl_ore", MapColor.STONE),
        Map.entry("borax_ore", MapColor.STONE),
        Map.entry("capacitor", MapColor.WOOL),
        Map.entry("cargo_hold", MapColor.STONE),
        Map.entry("cargo_loader", MapColor.TERRACOTTA_CYAN),
        Map.entry("cargo_terminal", MapColor.TERRACOTTA_CYAN),
        Map.entry("cascade_controller", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("catcher_net", MapColor.COLOR_GRAY),
        Map.entry("clutch", MapColor.DEEPSLATE),
        Map.entry("coal_generator", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("command_module", MapColor.CLAY),
        Map.entry("control_rod_drive", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("creative_power", MapColor.DEEPSLATE),
        Map.entry("crusher", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("crystal_puller", MapColor.WOOL),
        Map.entry("deepslate_titanium_ore", MapColor.COLOR_GRAY),
        Map.entry("deepslate_tungsten_ore", MapColor.COLOR_GRAY),
        Map.entry("despin_motor", MapColor.COLOR_LIGHT_GRAY),
        Map.entry("dish_mount", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("dish_panel", MapColor.QUARTZ),
        Map.entry("distillation_tray", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("docking_clamp", MapColor.STONE),
        Map.entry("dsn_controller", MapColor.WOOL),
        Map.entry("eaf_controller", MapColor.COLOR_GRAY),
        Map.entry("eaf_roof", MapColor.COLOR_GRAY),
        Map.entry("eaf_shell", MapColor.COLOR_BROWN),
        Map.entry("eclss_controller", MapColor.WOOL),
        Map.entry("eclss_rack_frame", MapColor.COLOR_LIGHT_GRAY),
        Map.entry("electric_furnace", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("electrolysis_cell", MapColor.GLOW_LICHEN),
        Map.entry("electrolyzer", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("energy_cable", MapColor.COLOR_GRAY),
        Map.entry("fan_filter_unit", MapColor.WOOL),
        Map.entry("fluorite_ore", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("fuel_tank", MapColor.WOOL),
        Map.entry("fueling_pump", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("galena_ore", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("gas_centrifuge", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("gas_tank", MapColor.STONE),
        Map.entry("gearbox", MapColor.TERRACOTTA_CYAN),
        Map.entry("grow_lamp", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("gyroscope", MapColor.DEEPSLATE),
        Map.entry("halite_ore", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("heat_pipe", MapColor.STONE),
        Map.entry("hermetic_hatch", MapColor.COLOR_BROWN),
        Map.entry("hull_plating", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("hydrolox_engine", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("hydroponic_tray", MapColor.DEEPSLATE),
        Map.entry("hyperspectral_satellite", MapColor.COLOR_LIGHT_GRAY),
        Map.entry("imaging_satellite", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("interceptor_dish", MapColor.STONE),
        Map.entry("landing_beacon", MapColor.COLOR_GRAY),
        Map.entry("lathe", MapColor.DEEPSLATE),
        Map.entry("launch_pad", MapColor.COLOR_GRAY),
        Map.entry("lunar_bricks", MapColor.STONE),
        Map.entry("mars_ice", MapColor.DIRT),
        Map.entry("mars_tungsten_ore", MapColor.TERRACOTTA_ORANGE),
        Map.entry("mass_catcher", MapColor.TERRACOTTA_WHITE),
        Map.entry("mass_driver_breech", MapColor.COLOR_GRAY),
        Map.entry("mechanical_press", MapColor.STONE),
        Map.entry("methalox_engine", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("mission_control", MapColor.COLOR_GRAY),
        Map.entry("module_hull", MapColor.WOOL),
        Map.entry("mono_solar_panel", MapColor.TERRACOTTA_CYAN),
        Map.entry("moon_ice", MapColor.WOOL),
        Map.entry("moon_regolith", MapColor.COLOR_LIGHT_GRAY),
        Map.entry("moon_stone", MapColor.DEEPSLATE),
        Map.entry("moon_titanium_ore", MapColor.DEEPSLATE),
        Map.entry("motor", MapColor.STONE),
        Map.entry("oil_shale", MapColor.COLOR_GRAY),
        Map.entry("orbital_cannon", MapColor.COLOR_GRAY),
        Map.entry("power_satellite", MapColor.COLOR_LIGHT_GRAY),
        Map.entry("radiator_panel", MapColor.WOOL),
        Map.entry("reactor_core", MapColor.COLOR_GRAY),
        Map.entry("reactor_power_cap", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("rectenna", MapColor.STONE),
        Map.entry("refinery", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("refractory_lining", MapColor.TERRACOTTA_LIGHT_GRAY),
        Map.entry("regolith_reactor", MapColor.TERRACOTTA_LIGHT_GRAY),
        Map.entry("return_capsule", MapColor.CLAY),
        Map.entry("rim_thruster", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("rocket_engine", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("rocket_hull", MapColor.WOOL),
        Map.entry("rocket_seat", MapColor.TERRACOTTA_BLUE),
        Map.entry("rover_charger", MapColor.COLOR_GRAY),
        Map.entry("rtg", MapColor.COLOR_BROWN),
        Map.entry("sabatier_reactor", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("sail", MapColor.QUARTZ),
        Map.entry("satellite", MapColor.TERRACOTTA_LIGHT_GRAY),
        Map.entry("sintered_regolith", MapColor.COLOR_LIGHT_GRAY),
        Map.entry("solar_panel", MapColor.TERRACOTTA_CYAN),
        Map.entry("spin_hub", MapColor.TERRACOTTA_CYAN),
        Map.entry("spodumene_ore", MapColor.TERRACOTTA_LIGHT_BLUE),
        Map.entry("stage_separator", MapColor.COLOR_GRAY),
        Map.entry("steel_coil", MapColor.PODZOL),
        Map.entry("stirling_convertor", MapColor.COLOR_LIGHT_GRAY),
        Map.entry("superconducting_coil", MapColor.COLOR_CYAN),
        Map.entry("telemetry_screen", MapColor.COLOR_GRAY),
        Map.entry("titanium_ore", MapColor.STONE),
        Map.entry("uraninite_ore", MapColor.COLOR_GRAY),
        Map.entry("vent_grate", MapColor.COLOR_GRAY),
        Map.entry("wafer_saw", MapColor.COLOR_LIGHT_GRAY),
        Map.entry("wind_hub", MapColor.STONE));

    private ModMapColors() {
    }

    /** Цвет блока на карте; NONE — прозрачен сверху (стекло) или невидимая модель. */
    public static MapColor of(String block) {
        return COLORS.getOrDefault(block, MapColor.NONE);
    }
}
